//
//  Goals.swift
//  Neural Loop
//
//  Created by Sanjeev Hayal on 05/01/2026.
//


//CREATE TABLE goals (
//    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    title TEXT NOT NULL,
//    lifearea_id BIGINT NOT NULL,
//    start_date TIMESTAMPTZ,
//    deadline TIMESTAMPTZ,
//    color TEXT,
//    description TEXT,
//    icon TEXT
//    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
//    patent_id: BIGINT
//
//    CONSTRAINT fk_goals_lifearea
//        FOREIGN KEY (lifearea_id)
//        REFERENCES life_areas(id)
//        ON DELETE CASCADE
//        ON UPDATE CASCADE
//
//    CONSTRAINT goals_parent_id_fkey
//        FOREIGN KEY (patent_id)
//        REFERENCES goals(id)
//        ON DELETE SET NULL
//        ON UPDATE CASCADE
//);
//
//CREATE INDEX idx_goals_lifearea_id ON goals(lifearea_id);
//CREATE INDEX idx_goals_deadline ON goals(deadline);
//CREATE INDEX idx_goals_start_date ON goals(start_date);

import Foundation
import Supabase

struct Goals: Codable, Identifiable {

    // MARK: - Properties
    var id: Int64?
    var title: String
    var lifearea_id: Int64
    var start_date: Date?          // ISO-8601: YYYY-MM-DD
    var deadline: Date?           // nullable
    var color: String?              // nullable
    var description: String?        // nullable
    var icon: String
    var is_completed: Bool
    var parent_id: Int64?
    private(set) var updated_at: Date = Date()
    
    private mutating func touch() {
            updated_at = Date()
        }
}

struct GoalDetailBundle: Codable {
    let goal: Goals
    let sub_goals: [Goals]
    let tasks: [Tasks]
    let habits: [Habits]
    let tracking: GoalsTracking?
    let tracking_records: [GoalsTrackingRecord]
}

extension DBManager {
    // NOTE:
    // Database indexes (PRIMARY KEY, foreign key indexes, composite indexes, etc.)
    // CANNOT be created or managed from Swift/Supabase client code.
    //
    // Indexes must be defined at the database level using SQL migrations
    // (e.g. in Supabase SQL editor or migration files).
    //
    // This Swift code will automatically benefit from those indexes when
    // queries use `.eq`, `.order`, `.limit`, etc.

    private var goalsTableName: String { "goals" }

    // MARK: - Create
    func addGoal(_ goal: Goals) async throws -> Goals {
        let inserted: [Goals] = try await customsupabase
            .from(self.goalsTableName)
            .insert(goal)
            .select()
            .execute()
            .value
        return inserted.first!
    }

    // MARK: - Read
    func fetchAllGoals() async throws -> [Goals] {
        try await customsupabase
            .from(self.goalsTableName)
            .select()
            .execute()
            .value as [Goals]
    }

    func fetchGoal(by idValue: Int64) async throws -> Goals? {
        let rows: [Goals] = try await customsupabase
            .from(self.goalsTableName)
            .select()
            .eq("id", value: Int(idValue))
            .limit(1)
            .execute()
            .value
        return rows.first
    }
    
    /// Fetches all data needed for one goal detail or progress screen.
    /// - Parameter goalId: goal ID.
    /// - Returns: A JSON object with the goal, sub-goals, linked tasks, linked habits, tracking config, and tracking records.
    func fetchGoalDetail(goalId: Int64) async throws -> GoalDetailBundle {
        return try await customsupabase
            .rpc("nl_get_goal_detail", params: ["p_goal_id": goalId])
            .execute()
            .value
    }
    
    func fetchGoalName(by idValue: Int64) async throws -> String? {
        let rows: [Goals] = try await customsupabase
            .from(self.goalsTableName)
            .select()
            .eq("id", value: Int(idValue))
            .limit(1)
            .execute()
            .value
        return rows.first?.title
    }
    

    func fetchGoalsForLifeArea(forLifeArea: Int64) async throws -> [Goals] {
        try await customsupabase
            .from(self.goalsTableName)
            .select()
            .eq("lifearea_id", value: Int(forLifeArea))
            .execute()
            .value as [Goals]
    }
    func fecthGoalsForParentId(forParentId: Int64, ignoreCompleted: Bool = false) async throws -> [Goals] {
        try await customsupabase
            .from(self.goalsTableName)
            .select()
            .eq("parent_id", value: Int(forParentId))
            .eq("is_completed", value: ignoreCompleted)
            .execute()
            .value as [Goals]
    }
    
    func fetchGoalsCount(forLifeArea lifeAreaIdValue: Int64) async throws -> Int {
        try await customsupabase
            .from(self.goalsTableName)
            .select("COUNT(*)")
            .eq("lifearea_id", value: Int(lifeAreaIdValue))
            .execute()
            .value!
    }

    // MARK: - Update
    func updateGoal(_ goal: Goals) async throws {
        guard let goalId = goal.id else { return }
        _ = try await customsupabase
            .from(self.goalsTableName)
            .update(goal)
            .eq("id", value: Int(goalId))
            .select()
            .execute()
    }

    // MARK: - Delete
    func deleteGoal(id goalId: Int64) async throws {
        _ = try await customsupabase
            .from(self.goalsTableName)
            .delete()
            .eq("id", value: Int(goalId))
            .execute()
    }

    func deleteGoals(forLifeArea lifeAreaIdValue: Int64) async throws {
        _ = try await customsupabase
            .from(self.goalsTableName)
            .delete()
            .eq("lifearea_id", value: Int(lifeAreaIdValue))
            .execute()
    }
}
