create table equipment (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table muscle (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table routine (
  id bigint generated by default as identity primary key,
  name text not null,
  notes text
);

create table exercise (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('rep-based', 'duration')),
  equipment_id bigint references equipment (id) on delete set null
);

create table exercise_muscles (
  id bigint generated by default as identity primary key,
  exercise_id bigint references exercise (id) on delete cascade not null,
  muscle_id bigint references muscle (id) on delete cascade not null,
  is_primary boolean default false not null,
  unique (exercise_id, muscle_id)
);

create table routine_exercise (
  id bigint generated by default as identity primary key,
  routine_id bigint references routine (id) on delete cascade not null,
  exercise_id bigint references exercise (id) on delete cascade not null,
  order_index integer not null,
  target_sets integer,
  target_reps integer,
  rest_seconds integer,
  superset_group_id integer,
  unique (routine_id, order_index)
);

create table workout_session (
  id bigint generated by default as identity primary key,
  date date default current_date not null,
  start_time time,
  end_time time,
  session_type text not null,
  notes text
);

create table workout_set (
  id bigint generated by default as identity primary key,
  workout_session_id bigint references workout_session (id) on delete cascade not null,
  exercise_id bigint references exercise (id) on delete cascade not null,
  set_number integer not null,
  reps integer not null,
  weight numeric,
  superset_group_id integer
);

create table cardio_log (
  id bigint generated by default as identity primary key,
  workout_session_id bigint references workout_session (id) on delete cascade not null,
  exercise_id bigint references exercise (id) on delete cascade not null,
  distance_meters numeric,
  duration_minutes numeric
);

create index idx_exercise_equipment_id on exercise(equipment_id);
create index idx_exercise_muscles_exercise_id on exercise_muscles(exercise_id);
create index idx_exercise_muscles_muscle_id on exercise_muscles(muscle_id);
create index idx_routine_exercise_routine_id on routine_exercise(routine_id);
create index idx_routine_exercise_exercise_id on routine_exercise(exercise_id);
create index idx_workout_session_date on workout_session(date);
create index idx_workout_set_session_id on workout_set(workout_session_id);
create index idx_workout_set_exercise_id on workout_set(exercise_id);
create index idx_cardio_log_session_id on cardio_log(workout_session_id);
create index idx_cardio_log_exercise_id on cardio_log(exercise_id);
