begin;

create table public.task_map_links (
    id bigint generated by default as identity primary key,
    task_id bigint not null
        references public.tasks (id)
        on delete cascade,
    place_id bigint
        references public.map_places (id)
        on delete cascade,
    route_id bigint
        references public.map_routes (id)
        on delete cascade,
    relationship text not null default 'reference'
        check (relationship in ('owner', 'reference')),
    position integer not null default 0
        check (position >= 0),
    client_draft_id uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint task_map_links_one_target_check check (
        (place_id is not null and route_id is null)
        or (place_id is null and route_id is not null)
    ),
    constraint task_map_links_route_reference_only_check check (
        route_id is null or relationship = 'reference'
    ),
    constraint task_map_links_client_draft_owner_only_check check (
        client_draft_id is null
        or (relationship = 'owner' and place_id is not null)
    )
);

comment on table public.task_map_links is
    'Live task relationships for saved map places and routes. Owner links are exclusive, task-created places.';

create index task_map_links_task_position_idx
    on public.task_map_links (task_id, position, id);

create index task_map_links_place_idx
    on public.task_map_links (place_id, task_id)
    where place_id is not null;

create index task_map_links_route_idx
    on public.task_map_links (route_id, task_id)
    where route_id is not null;

create unique index task_map_links_task_place_unique_idx
    on public.task_map_links (task_id, place_id)
    where place_id is not null;

create unique index task_map_links_task_route_unique_idx
    on public.task_map_links (task_id, route_id)
    where route_id is not null;

create unique index task_map_links_one_place_owner_idx
    on public.task_map_links (place_id)
    where relationship = 'owner' and place_id is not null;

create unique index task_map_links_client_draft_unique_idx
    on public.task_map_links (client_draft_id)
    where client_draft_id is not null;

create or replace function public.nl_touch_task_map_link_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger touch_task_map_links_updated_at
before update on public.task_map_links
for each row execute function public.nl_touch_task_map_link_updated_at();

create or replace function public.nl_validate_task_map_link()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_place public.map_places;
    v_default_folder_id bigint;
begin
    if new.route_id is not null then
        if new.relationship <> 'reference' then
            raise exception 'Routes can only be linked as references';
        end if;
        return new;
    end if;

    select place.*
    into v_place
    from public.map_places as place
    where place.id = new.place_id
    for update;

    if not found then
        raise exception 'Map place % does not exist', new.place_id;
    end if;

    if v_place.kind <> 'saved' then
        raise exception 'Parked places cannot be linked to tasks';
    end if;

    if new.relationship = 'owner' then
        select folder.id
        into v_default_folder_id
        from public.map_folders as folder
        where folder.is_default = true;

        if v_default_folder_id is null then
            raise exception 'The Unfiled folder is missing';
        end if;

        if v_place.folder_id <> v_default_folder_id then
            raise exception 'Task-owned places must remain in Unfiled';
        end if;

        if exists (
            select 1
            from public.task_map_links as existing
            where existing.place_id = new.place_id
              and existing.id <> new.id
        ) then
            raise exception 'A task-owned place cannot have other task links';
        end if;
    elsif exists (
        select 1
        from public.task_map_links as existing
        where existing.place_id = new.place_id
          and existing.relationship = 'owner'
          and existing.id <> new.id
    ) then
        raise exception 'Save the task-owned place permanently before linking it to another task';
    end if;

    return new;
end;
$$;

create trigger validate_task_map_link
before insert or update of place_id, route_id, relationship
on public.task_map_links
for each row execute function public.nl_validate_task_map_link();

create or replace function public.nl_protect_task_owned_map_place()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    if new.folder_id is distinct from old.folder_id
       and exists (
           select 1
           from public.task_map_links as link
           where link.place_id = old.id
             and link.relationship = 'owner'
       ) then
        raise exception 'Save this task-owned place permanently before moving it';
    end if;

    if new.kind = 'parked'
       and new.kind is distinct from old.kind
       and exists (
           select 1
           from public.task_map_links as link
           where link.place_id = old.id
       ) then
        raise exception 'A task-linked place cannot become a parked place';
    end if;

    return new;
end;
$$;

create trigger protect_task_owned_map_place
before update of folder_id, kind on public.map_places
for each row execute function public.nl_protect_task_owned_map_place();

create or replace function public.nl_delete_task_owned_map_places()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    delete from public.map_places as place
    where place.id in (
        select link.place_id
        from public.task_map_links as link
        where link.task_id = old.id
          and link.relationship = 'owner'
          and link.place_id is not null
    );

    return old;
end;
$$;

create trigger delete_task_owned_map_places
before delete on public.tasks
for each row execute function public.nl_delete_task_owned_map_places();

create or replace function public.nl_get_task_map_attachments(p_task_id bigint)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
    select coalesce(jsonb_agg(
        jsonb_build_object(
            'id', link.id,
            'task_id', link.task_id,
            'task_title', task.title,
            'place_id', link.place_id,
            'route_id', link.route_id,
            'relationship', link.relationship,
            'position', link.position,
            'client_draft_id', link.client_draft_id,
            'created_at', link.created_at,
            'updated_at', link.updated_at,
            'place', case when link.place_id is not null then to_jsonb(place) else null end,
            'route', case when link.route_id is not null then to_jsonb(route) else null end,
            'route_waypoints', case
                when link.route_id is null then '[]'::jsonb
                else coalesce((
                    select jsonb_agg(to_jsonb(waypoint) order by waypoint.order_index, waypoint.id)
                    from public.map_route_waypoints as waypoint
                    where waypoint.route_id = link.route_id
                ), '[]'::jsonb)
            end
        ) order by link.position, link.id
    ), '[]'::jsonb)
    from public.task_map_links as link
    join public.tasks as task on task.id = link.task_id
    left join public.map_places as place on place.id = link.place_id
    left join public.map_routes as route on route.id = link.route_id
    where link.task_id = p_task_id;
$$;

create or replace function public.nl_get_task_map_delete_impact(p_task_id bigint)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
    v_task_title text;
begin
    select task.title
    into v_task_title
    from public.tasks as task
    where task.id = p_task_id;

    if not found then
        raise exception 'Task % does not exist', p_task_id;
    end if;

    return jsonb_build_object(
        'task_id', p_task_id,
        'task_title', v_task_title,
        'owned_place_count', (
            select count(*)
            from public.task_map_links as link
            where link.task_id = p_task_id
              and link.relationship = 'owner'
              and link.place_id is not null
        ),
        'reference_place_count', (
            select count(*)
            from public.task_map_links as link
            where link.task_id = p_task_id
              and link.relationship = 'reference'
              and link.place_id is not null
        ),
        'reference_route_count', (
            select count(*)
            from public.task_map_links as link
            where link.task_id = p_task_id
              and link.route_id is not null
        ),
        'owned_places', coalesce((
            select jsonb_agg(to_jsonb(place) order by link.position, link.id)
            from public.task_map_links as link
            join public.map_places as place on place.id = link.place_id
            where link.task_id = p_task_id
              and link.relationship = 'owner'
        ), '[]'::jsonb)
    );
end;
$$;

create or replace function public.nl_get_map_place_link_impact(p_place_id bigint)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
    select jsonb_build_object(
        'place_id', p_place_id,
        'link_count', count(link.id),
        'links', coalesce(jsonb_agg(
            jsonb_build_object(
                'link_id', link.id,
                'task_id', task.id,
                'task_title', task.title,
                'relationship', link.relationship
            ) order by lower(task.title), task.id
        ) filter (where link.id is not null), '[]'::jsonb)
    )
    from public.map_places as place
    left join public.task_map_links as link on link.place_id = place.id
    left join public.tasks as task on task.id = link.task_id
    where place.id = p_place_id
    group by place.id;
$$;

create or replace function public.nl_apply_task_map_bundle(
    p_task_id bigint,
    p_references jsonb default '[]'::jsonb,
    p_owned_places jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_default_folder_id bigint;
    v_record record;
    v_place_id bigint;
    v_route_id bigint;
    v_position integer;
    v_client_draft_id uuid;
    v_existing_place_id bigint;
begin
    if jsonb_typeof(coalesce(p_references, '[]'::jsonb)) <> 'array' then
        raise exception 'p_references must be a JSON array';
    end if;

    if jsonb_typeof(coalesce(p_owned_places, '[]'::jsonb)) <> 'array' then
        raise exception 'p_owned_places must be a JSON array';
    end if;

    perform 1
    from public.tasks as task
    where task.id = p_task_id
    for update;

    if not found then
        raise exception 'Task % does not exist', p_task_id;
    end if;

    select folder.id
    into v_default_folder_id
    from public.map_folders as folder
    where folder.is_default = true
    for update;

    if v_default_folder_id is null then
        raise exception 'The Unfiled folder is missing';
    end if;

    delete from public.task_map_links
    where task_id = p_task_id
      and relationship = 'reference';

    for v_record in
        select item.value as item, item.ordinality
        from jsonb_array_elements(coalesce(p_references, '[]'::jsonb))
             with ordinality as item(value, ordinality)
    loop
        v_place_id := nullif(v_record.item ->> 'place_id', '')::bigint;
        v_route_id := nullif(v_record.item ->> 'route_id', '')::bigint;
        v_position := coalesce(
            nullif(v_record.item ->> 'position', '')::integer,
            (v_record.ordinality - 1)::integer
        );

        if (v_place_id is null) = (v_route_id is null) then
            raise exception 'Each reference must contain exactly one of place_id or route_id';
        end if;

        insert into public.task_map_links (
            task_id, place_id, route_id, relationship, position
        ) values (
            p_task_id, v_place_id, v_route_id, 'reference', v_position
        );
    end loop;

    for v_record in
        select item.value as item, item.ordinality
        from jsonb_array_elements(coalesce(p_owned_places, '[]'::jsonb))
             with ordinality as item(value, ordinality)
    loop
        v_client_draft_id := nullif(v_record.item ->> 'client_draft_id', '')::uuid;
        v_position := coalesce(
            nullif(v_record.item ->> 'position', '')::integer,
            (jsonb_array_length(coalesce(p_references, '[]'::jsonb)) + v_record.ordinality - 1)::integer
        );

        if v_client_draft_id is null then
            raise exception 'Each owned place requires client_draft_id';
        end if;

        select link.place_id
        into v_existing_place_id
        from public.task_map_links as link
        where link.task_id = p_task_id
          and link.client_draft_id = v_client_draft_id
          and link.relationship = 'owner'
        for update;

        if found then
            update public.task_map_links
            set position = v_position
            where task_id = p_task_id
              and client_draft_id = v_client_draft_id;
        else
            insert into public.map_places (
                folder_id, name, latitude, longitude, address, kind
            ) values (
                v_default_folder_id,
                btrim(v_record.item ->> 'name'),
                (v_record.item ->> 'latitude')::double precision,
                (v_record.item ->> 'longitude')::double precision,
                nullif(btrim(v_record.item ->> 'address'), ''),
                'saved'
            ) returning id into v_place_id;

            insert into public.task_map_links (
                task_id, place_id, relationship, position, client_draft_id
            ) values (
                p_task_id, v_place_id, 'owner', v_position, v_client_draft_id
            );
        end if;
    end loop;

    return public.nl_get_task_map_attachments(p_task_id);
end;
$$;

create or replace function public.nl_create_task_owned_place(
    p_task_id bigint,
    p_client_draft_id uuid,
    p_name text,
    p_latitude double precision,
    p_longitude double precision,
    p_address text default null,
    p_position integer default 0
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_default_folder_id bigint;
    v_place_id bigint;
begin
    perform 1
    from public.tasks as task
    where task.id = p_task_id
    for update;

    if not found then
        raise exception 'Task % does not exist', p_task_id;
    end if;

    select link.place_id
    into v_place_id
    from public.task_map_links as link
    where link.task_id = p_task_id
      and link.client_draft_id = p_client_draft_id
      and link.relationship = 'owner'
    for update;

    if found then
        return to_jsonb((
            select place
            from public.map_places as place
            where place.id = v_place_id
        ));
    end if;

    select folder.id
    into v_default_folder_id
    from public.map_folders as folder
    where folder.is_default = true
    for update;

    if v_default_folder_id is null then
        raise exception 'The Unfiled folder is missing';
    end if;

    insert into public.map_places (
        folder_id, name, latitude, longitude, address, kind
    ) values (
        v_default_folder_id,
        btrim(p_name),
        p_latitude,
        p_longitude,
        nullif(btrim(p_address), ''),
        'saved'
    ) returning id into v_place_id;

    insert into public.task_map_links (
        task_id, place_id, relationship, position, client_draft_id
    ) values (
        p_task_id, v_place_id, 'owner', p_position, p_client_draft_id
    );

    return to_jsonb((
        select place
        from public.map_places as place
        where place.id = v_place_id
    ));
end;
$$;

create or replace function public.nl_save_task_owned_place(
    p_task_id bigint,
    p_place_id bigint,
    p_folder_id bigint,
    p_name text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_link_id bigint;
    v_place public.map_places;
begin
    select link.id
    into v_link_id
    from public.task_map_links as link
    where link.task_id = p_task_id
      and link.place_id = p_place_id
      and link.relationship = 'owner'
    for update;

    if not found then
        raise exception 'Task % does not own place %', p_task_id, p_place_id;
    end if;

    perform 1
    from public.map_folders as folder
    where folder.id = p_folder_id
    for update;

    if not found then
        raise exception 'Folder % does not exist', p_folder_id;
    end if;

    update public.task_map_links
    set relationship = 'reference',
        client_draft_id = null
    where id = v_link_id;

    update public.map_places
    set folder_id = p_folder_id,
        name = coalesce(nullif(btrim(p_name), ''), name)
    where id = p_place_id
    returning * into v_place;

    return to_jsonb(v_place);
end;
$$;

create or replace function public.nl_remove_task_map_reference(
    p_task_id bigint,
    p_place_id bigint default null,
    p_route_id bigint default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_link public.task_map_links;
begin
    if (p_place_id is null) = (p_route_id is null) then
        raise exception 'Provide exactly one of p_place_id or p_route_id';
    end if;

    delete from public.task_map_links
    where task_id = p_task_id
      and relationship = 'reference'
      and place_id is not distinct from p_place_id
      and route_id is not distinct from p_route_id
    returning * into v_link;

    if not found then
        raise exception 'Reference link does not exist';
    end if;

    return to_jsonb(v_link);
end;
$$;

create or replace function public.nl_delete_task_owned_place(
    p_task_id bigint,
    p_place_id bigint
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_place public.map_places;
begin
    perform 1
    from public.task_map_links as link
    where link.task_id = p_task_id
      and link.place_id = p_place_id
      and link.relationship = 'owner'
    for update;

    if not found then
        raise exception 'Task % does not own place %', p_task_id, p_place_id;
    end if;

    delete from public.map_places
    where id = p_place_id
    returning * into v_place;

    return to_jsonb(v_place);
end;
$$;

create or replace function public.nl_delete_task(
    p_task_id bigint,
    p_preserved_places jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_owned_count integer;
    v_reference_place_count integer;
    v_reference_route_count integer;
    v_preserved_count integer := 0;
    v_record record;
    v_place_id bigint;
    v_folder_id bigint;
    v_link_id bigint;
begin
    if jsonb_typeof(coalesce(p_preserved_places, '[]'::jsonb)) <> 'array' then
        raise exception 'p_preserved_places must be a JSON array';
    end if;

    perform 1
    from public.tasks as task
    where task.id = p_task_id
    for update;

    if not found then
        raise exception 'Task % does not exist', p_task_id;
    end if;

    select
        count(*) filter (where relationship = 'owner' and place_id is not null),
        count(*) filter (where relationship = 'reference' and place_id is not null),
        count(*) filter (where route_id is not null)
    into v_owned_count, v_reference_place_count, v_reference_route_count
    from public.task_map_links
    where task_id = p_task_id;

    for v_record in
        select item.value as item
        from jsonb_array_elements(coalesce(p_preserved_places, '[]'::jsonb)) as item(value)
    loop
        v_place_id := nullif(v_record.item ->> 'place_id', '')::bigint;
        v_folder_id := nullif(v_record.item ->> 'folder_id', '')::bigint;

        if v_place_id is null or v_folder_id is null then
            raise exception 'Each preserved place requires place_id and folder_id';
        end if;

        select link.id
        into v_link_id
        from public.task_map_links as link
        where link.task_id = p_task_id
          and link.place_id = v_place_id
          and link.relationship = 'owner'
        for update;

        if not found then
            raise exception 'Task % does not own place %', p_task_id, v_place_id;
        end if;

        update public.task_map_links
        set relationship = 'reference',
            client_draft_id = null
        where id = v_link_id;

        update public.map_places
        set folder_id = v_folder_id,
            name = coalesce(nullif(btrim(v_record.item ->> 'name'), ''), name)
        where id = v_place_id;

        v_preserved_count := v_preserved_count + 1;
    end loop;

    delete from public.tasks
    where id = p_task_id;

    return jsonb_build_object(
        'deleted_task_id', p_task_id,
        'deleted_owned_place_count', v_owned_count - v_preserved_count,
        'preserved_place_count', v_preserved_count,
        'removed_reference_place_count', v_reference_place_count,
        'removed_reference_route_count', v_reference_route_count
    );
end;
$$;

create or replace function public.nl_get_maps_snapshot()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
    select jsonb_build_object(
        'folders', coalesce((
            select jsonb_agg(to_jsonb(folder) order by folder.is_default desc, lower(folder.name), folder.id)
            from public.map_folders as folder
        ), '[]'::jsonb),
        'places', coalesce((
            select jsonb_agg(to_jsonb(place) order by lower(place.name), place.id)
            from public.map_places as place
        ), '[]'::jsonb),
        'routes', coalesce((
            select jsonb_agg(to_jsonb(route) order by lower(route.name), route.id)
            from public.map_routes as route
        ), '[]'::jsonb),
        'route_waypoints', coalesce((
            select jsonb_agg(to_jsonb(waypoint) order by waypoint.route_id, waypoint.order_index, waypoint.id)
            from public.map_route_waypoints as waypoint
        ), '[]'::jsonb),
        'task_links', coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'id', link.id,
                    'task_id', link.task_id,
                    'task_title', task.title,
                    'place_id', link.place_id,
                    'route_id', link.route_id,
                    'relationship', link.relationship,
                    'position', link.position,
                    'client_draft_id', link.client_draft_id,
                    'created_at', link.created_at,
                    'updated_at', link.updated_at
                ) order by lower(task.title), task.id, link.position, link.id
            )
            from public.task_map_links as link
            join public.tasks as task on task.id = link.task_id
        ), '[]'::jsonb)
    );
$$;

alter table public.task_map_links enable row level security;

create policy task_map_links_anon_select
on public.task_map_links
for select to anon
using (true);

create policy task_map_links_anon_insert
on public.task_map_links
for insert to anon
with check (true);

create policy task_map_links_anon_update
on public.task_map_links
for update to anon
using (true)
with check (true);

create policy task_map_links_anon_delete_references
on public.task_map_links
for delete to anon
using (relationship = 'reference');

grant select, insert, update, delete
on table public.task_map_links
to anon;

grant usage, select
on sequence public.task_map_links_id_seq
to anon;

revoke all on function public.nl_touch_task_map_link_updated_at() from public, anon, authenticated;
revoke all on function public.nl_validate_task_map_link() from public, anon, authenticated;
revoke all on function public.nl_protect_task_owned_map_place() from public, anon, authenticated;
revoke all on function public.nl_delete_task_owned_map_places() from public, anon, authenticated;

revoke all on function public.nl_get_task_map_attachments(bigint) from public, anon, authenticated;
revoke all on function public.nl_get_task_map_delete_impact(bigint) from public, anon, authenticated;
revoke all on function public.nl_get_map_place_link_impact(bigint) from public, anon, authenticated;
revoke all on function public.nl_apply_task_map_bundle(bigint, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.nl_create_task_owned_place(bigint, uuid, text, double precision, double precision, text, integer) from public, anon, authenticated;
revoke all on function public.nl_save_task_owned_place(bigint, bigint, bigint, text) from public, anon, authenticated;
revoke all on function public.nl_remove_task_map_reference(bigint, bigint, bigint) from public, anon, authenticated;
revoke all on function public.nl_delete_task_owned_place(bigint, bigint) from public, anon, authenticated;
revoke all on function public.nl_delete_task(bigint, jsonb) from public, anon, authenticated;
revoke all on function public.nl_get_maps_snapshot() from public, anon, authenticated;

grant execute on function public.nl_get_task_map_attachments(bigint) to anon;
grant execute on function public.nl_get_task_map_delete_impact(bigint) to anon;
grant execute on function public.nl_get_map_place_link_impact(bigint) to anon;
grant execute on function public.nl_apply_task_map_bundle(bigint, jsonb, jsonb) to anon;
grant execute on function public.nl_create_task_owned_place(bigint, uuid, text, double precision, double precision, text, integer) to anon;
grant execute on function public.nl_save_task_owned_place(bigint, bigint, bigint, text) to anon;
grant execute on function public.nl_remove_task_map_reference(bigint, bigint, bigint) to anon;
grant execute on function public.nl_delete_task_owned_place(bigint, bigint) to anon;
grant execute on function public.nl_delete_task(bigint, jsonb) to anon;
grant execute on function public.nl_get_maps_snapshot() to anon;

commit;
