begin;

create table public.map_folders (
    id bigint generated by default as identity primary key,
    name text not null
        check (name = btrim(name))
        check (char_length(name) between 1 and 100),
    description text
        check (description is null or char_length(description) <= 500),
    is_default boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index map_folders_name_unique_idx
    on public.map_folders (lower(btrim(name)));

create unique index map_folders_one_default_idx
    on public.map_folders (is_default)
    where is_default = true;

create table public.map_places (
    id bigint generated by default as identity primary key,
    folder_id bigint not null
        references public.map_folders (id)
        on delete restrict,
    name text not null
        check (name = btrim(name))
        check (char_length(name) between 1 and 100),
    latitude double precision not null
        check (latitude between -90 and 90),
    longitude double precision not null
        check (longitude between -180 and 180),
    address text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.map_routes (
    id bigint generated by default as identity primary key,
    folder_id bigint not null
        references public.map_folders (id)
        on delete restrict,
    name text not null
        check (name = btrim(name))
        check (char_length(name) between 1 and 100),
    transport_mode text not null
        check (transport_mode in ('automobile', 'walking', 'cycling', 'transit')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.map_route_waypoints (
    id bigint generated by default as identity primary key,
    route_id bigint not null
        references public.map_routes (id)
        on delete cascade,
    order_index integer not null check (order_index >= 0),
    latitude double precision not null
        check (latitude between -90 and 90),
    longitude double precision not null
        check (longitude between -180 and 180),
    emoji text,
    created_at timestamptz not null default now(),
    unique (route_id, order_index)
);

create index map_places_folder_name_idx
    on public.map_places (folder_id, lower(name), id);

create index map_routes_folder_name_idx
    on public.map_routes (folder_id, lower(name), id);

create index map_route_waypoints_route_idx
    on public.map_route_waypoints (route_id, order_index);

insert into public.map_folders (name, description, is_default)
values (
    'Unfiled',
    'Places and routes without an assigned folder.',
    true
);

create or replace function public.nl_protect_default_map_folder()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    if tg_op = 'DELETE' and old.is_default then
        raise exception 'The Unfiled folder cannot be deleted';
    end if;

    if tg_op = 'UPDATE' then
        if new.is_default is distinct from old.is_default then
            raise exception 'The default-folder status cannot be changed';
        end if;

        if old.is_default and new.name is distinct from old.name then
            raise exception 'The Unfiled folder cannot be renamed';
        end if;
    end if;

    if tg_op = 'DELETE' then
        return old;
    end if;

    return new;
end;
$$;

create trigger protect_default_map_folder
before update or delete on public.map_folders
for each row execute function public.nl_protect_default_map_folder();

create or replace function public.nl_touch_map_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger touch_map_folders_updated_at
before update on public.map_folders
for each row execute function public.nl_touch_map_updated_at();

create trigger touch_map_places_updated_at
before update on public.map_places
for each row execute function public.nl_touch_map_updated_at();

create trigger touch_map_routes_updated_at
before update on public.map_routes
for each row execute function public.nl_touch_map_updated_at();

create or replace function public.nl_validate_map_route_row()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    if (
        select count(*)
        from public.map_route_waypoints as waypoint
        where waypoint.route_id = new.id
    ) < 2 then
        raise exception 'A map route requires at least two waypoints';
    end if;

    return null;
end;
$$;

create constraint trigger validate_map_route_row
after insert or update on public.map_routes
deferrable initially deferred
for each row execute function public.nl_validate_map_route_row();

create or replace function public.nl_validate_map_route_waypoint_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_route_id bigint;
begin
    for v_route_id in
        select distinct route_id
        from (
            select case when tg_op <> 'DELETE' then new.route_id end as route_id
            union all
            select case when tg_op <> 'INSERT' then old.route_id end as route_id
        ) as affected
        where route_id is not null
    loop
        if exists (
            select 1
            from public.map_routes as route
            where route.id = v_route_id
        ) and (
            select count(*)
            from public.map_route_waypoints as waypoint
            where waypoint.route_id = v_route_id
        ) < 2 then
            raise exception 'A map route requires at least two waypoints';
        end if;
    end loop;

    return null;
end;
$$;

create constraint trigger validate_map_route_waypoint_change
after insert or update or delete on public.map_route_waypoints
deferrable initially deferred
for each row execute function public.nl_validate_map_route_waypoint_change();

create or replace function public.nl_get_maps_snapshot()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
    select jsonb_build_object(
        'folders', coalesce((
            select jsonb_agg(to_jsonb(folder) order by folder.is_default desc, lower(folder.name), folder.id)
            from public.map_folders as folder
        ), '[]'::jsonb),
        'places', coalesce((
            select jsonb_agg(to_jsonb(place) order by lower(place.name), place.id)
            from public.map_places as place
        ), '[]'::jsonb),
        'routes', coalesce((
            select jsonb_agg(to_jsonb(route) order by lower(route.name), route.id)
            from public.map_routes as route
        ), '[]'::jsonb),
        'route_waypoints', coalesce((
            select jsonb_agg(to_jsonb(waypoint) order by waypoint.route_id, waypoint.order_index, waypoint.id)
            from public.map_route_waypoints as waypoint
        ), '[]'::jsonb)
    );
$$;

create or replace function public.nl_delete_map_folder(p_folder_id bigint)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_default_id bigint;
    v_place_count integer;
    v_route_count integer;
begin
    select folder.id
    into v_default_id
    from public.map_folders as folder
    where folder.is_default = true
    for update;

    if v_default_id is null then
        raise exception 'The Unfiled folder is missing';
    end if;

    if p_folder_id = v_default_id then
        raise exception 'The Unfiled folder cannot be deleted';
    end if;

    perform 1
    from public.map_folders as folder
    where folder.id = p_folder_id
    for update;

    if not found then
        raise exception 'Folder % does not exist', p_folder_id;
    end if;

    update public.map_places
    set folder_id = v_default_id
    where folder_id = p_folder_id;

    get diagnostics v_place_count = row_count;

    update public.map_routes
    set folder_id = v_default_id
    where folder_id = p_folder_id;

    get diagnostics v_route_count = row_count;

    delete from public.map_folders
    where id = p_folder_id;

    return jsonb_build_object(
        'deleted_folder_id', p_folder_id,
        'moved_place_count', v_place_count,
        'moved_route_count', v_route_count
    );
end;
$$;

alter table public.map_folders enable row level security;
alter table public.map_places enable row level security;
alter table public.map_routes enable row level security;
alter table public.map_route_waypoints enable row level security;

create policy map_folders_anon_all
on public.map_folders
for all to anon
using (true)
with check (true);

create policy map_places_anon_all
on public.map_places
for all to anon
using (true)
with check (true);

create policy map_routes_anon_all
on public.map_routes
for all to anon
using (true)
with check (true);

create policy map_route_waypoints_anon_all
on public.map_route_waypoints
for all to anon
using (true)
with check (true);

grant select, insert, update, delete
on table public.map_folders,
         public.map_places,
         public.map_routes,
         public.map_route_waypoints
to anon;

grant usage, select
on sequence public.map_folders_id_seq,
            public.map_places_id_seq,
            public.map_routes_id_seq,
            public.map_route_waypoints_id_seq
to anon;

revoke all on function public.nl_protect_default_map_folder() from public, anon, authenticated;
revoke all on function public.nl_touch_map_updated_at() from public, anon, authenticated;
revoke all on function public.nl_validate_map_route_row() from public, anon, authenticated;
revoke all on function public.nl_validate_map_route_waypoint_change() from public, anon, authenticated;
revoke all on function public.nl_get_maps_snapshot() from public, anon, authenticated;
revoke all on function public.nl_delete_map_folder(bigint) from public, anon, authenticated;

grant execute on function public.nl_get_maps_snapshot() to anon;
grant execute on function public.nl_delete_map_folder(bigint) to anon;

commit;
